create table animals (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    body jsonb not null,
    constraint animals_pkey primary key (id)
);

alter table animals
    enable row level security;
create policy "Enable read access for all users"
    on animals
    for select using (true);

create unique index animals_desertion_no_idx on animals using btree (((body -> 'desertionNo'::text)));
